In [2]:
import numpy as np

m=2;n=4;alpha=0.95;

p0=np.array([
              [0.1, 0.3, 0.6, 0.0],
              [0.0, 0.2, 0.5, 0.3],
              [0.1, 0.1, 0.2, 0.7],
              [0.8, 0.1, 0.0, 0.1]
            ])
p1=np.array([
              [0.6, 0.3, 0.1, 0.0],
              [0.75, 0.1, 0.1, 0.05],
              [0.8, 0.2, 0.0, 0.0],
              [0.9, 0.1, 0.0, 0.0]
            ])
p=[p0,p1]


f0=np.array([100,125,150,500])
f1=np.array([300, 325, 350, 600])
f=[f0,f1]

v=np.zeros(n)
delta=100; epsilon=0.0001;

while (delta>epsilon):
    q=np.zeros((m,n))
    for i in range(m):
          q[i]=f[i]+alpha*p[i].dot(v)
    w=q[0]
    
    for i in range(n):
        for j in range(m):
            if q[j][i]<w[i]:
                w[i]=q[j][i]
    delta=max(abs(v-w))
    v=w
    print(v)
    


for i in range(m):
    q[i]=f[i]+alpha*p[i].dot(v)
w=q[0]
a=np.zeros(n,dtype=np.int64)
for i in range(n):
     for j in range(m):
          if q[j][i]<w[i]:
              w[i]=q[j][i]
              a[i]=j
print(a)
    




[100. 125. 150. 500.]
[230.625 362.5   449.75  635.375]
[481.579375 588.588125 594.15     770.073125]
[652.16315625 738.52383437 827.83206875 995.07314375]
[ 844.29907183  942.13560716  985.96352728 1160.33571167]
[1010.71627041 1103.03411864 1170.67305995 1341.40206988]
[1177.66641367 1272.94577593 1327.72084806 1500.36580342]
[1331.46873883 1425.13135423 1486.88617182 1658.49107443]
[1480.17708408 1574.71584513 1632.69119882 1804.86037224]
[1620.04482218 1714.1095361  1774.13059448 1945.99432455]
[1753.67991475 1848.00122673 1906.91487671 2078.94393162]
[1880.22142125 1974.40382003 2033.91696829 2205.85652525]
[2000.65879565 2094.91639544 2154.10500595 2326.09301295]
[2114.95361168 2209.17050165 2268.53479983 2440.49657849]
[2223.59902198 2317.8379501  2377.10714019 2549.08311749]
[2326.77679278 2421.00379059 2480.32446723 2652.29275813]
[2424.81482195 2519.04827821 2578.34108272 2750.31353464]
[2517.94058453 2612.17054452 2671.47843754 2843.4486369 ]
[2606.41567012 2700.64752281 275