<a href="https://colab.research.google.com/github/ngohieu12/NgauNhien/blob/master/ViDu/Vi_du_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
n=4;

m=2;n=4;alpha=0.95;

I=np.eye(n);
A=np.eye(n+1)
A[n][0]=1
A[n][n]=0
for i in range(n):
    A[i][n]=1
    

I=np.eye(n);

p0=np.array([
              [0.1, 0.3, 0.6, 0.0],
              [0.0, 0.2, 0.5, 0.3],
              [0.1, 0.1, 0.2, 0.7],
              [0.8, 0.1, 0.0, 0.1]
            ])
p1=np.array([
              [0.6, 0.3, 0.1, 0.0],
              [0.75, 0.1, 0.1, 0.05],
              [0.8, 0.2, 0.0, 0.0],
              [0.9, 0.1, 0.0, 0.0]
            ])
p=[p0,p1]


f0=np.array([100,125,150,500])
f1=np.array([300, 325, 350, 600])
f=[f0,f1]

w=f[0]
a=np.zeros(n, dtype=np.int64)
g=np.zeros(n+1)
v=np.zeros(n+1)
h=np.zeros(n)


for i in range(n):
              for j in range(m):
                  if f[j][i]<w[i]:
                        w[i]=f[j][i]
                        a[i]=j

delta=100; epsilon=0.5

while (delta>epsilon):

           print(a) 
     
           for i in range(n):
               g[i]=f[a[i]][i]
           g[n]=0
         
          
           
           q=np.zeros((n+1,n+1))
           for i in range(n):
               for j in range(n):
                   q[i][j]=p[a[i]][i][j]
           for i in range(n):
               q[i][n]=q[n][i]=0
        
           v=np.linalg.inv(A-q).dot(g)  
           print(v) 
          
           
           for i in range(n):
               h[i]=v[i]
           
           
           k=np.zeros((m,n))
           for i in range(m):
                k[i]=f[i]+p[i].dot(h)
           w=k[0]
           
          
           b=np.zeros(n, dtype=np.int64)
           for i in range(n):
                 for j in range(m):
                     if k[j][i]<w[i]:
                         w[i]=k[j][i]
                         b[i]=j
            
           delta=max(abs(a-b))
           a=b
           
          





    



[0 0 0 0]
[  0.          90.39699571 176.23390558 306.86695279 232.85944206]
[0 0 1 0]
[  0.          97.09618875 150.1814882  322.74652148 219.23774955]
